"""EQBuddy Evolved launch trailer - the score, synthesized from nothing.

No samples and no licensed audio: every sound below is arithmetic, so the trailer carries
no Content ID claim and the track can be regenerated byte-for-byte from this file.

    python scripts/trailer/score.py out.wav

96 BPM, D minor, 25 bars (62.5 s) plus a reverb tail. The bar map is the edit's map -
timeline.json cuts on these same bar lines, so a change here is a change to both.

    bars  0-1   cold open        pad + drone, reverse swell
    bar   2     logo             impact
    bars  2-3   logo             pad, riser into bar 4
    bars  4-19  features         drums, pulse bass, arp (arp from bar 8)
    bars 19-20  map / phone      fill + lift
    bars 21-22  principles       breakdown: pads + bell line, riser into bar 23
    bars 23-24  end card         final impact, held chord, tail
"""
import sys
import numpy as np
from scipy.signal import butter, sosfilt, fftconvolve

SR = 44100
BPM = 96.0
BEAT = 60.0 / BPM
BAR = BEAT * 4
BARS = 25
TAIL = 3.0
N = int((BARS * BAR + TAIL) * SR)
rng = np.random.default_rng(20260928)


def t_of(n):
    return np.arange(n) / SR


def midi_hz(m):
    return 440.0 * 2 ** ((m - 69) / 12.0)


def lp(x, hz, order=2):
    return sosfilt(butter(order, hz, 'low', fs=SR, output='sos'), x)


def hp(x, hz, order=2):
    return sosfilt(butter(order, hz, 'high', fs=SR, output='sos'), x)


def bp(x, lo, hi, order=2):
    return sosfilt(butter(order, [lo, hi], 'band', fs=SR, output='sos'), x)


def saw(freq, n, phase=0.0):
    ph = (phase + np.cumsum(np.full(n, freq) if np.isscalar(freq) else freq) / SR) % 1.0
    return 2.0 * ph - 1.0


def adsr(n, a, d, s, r):
    env = np.full(n, s, dtype=float)
    na, nd, nr = int(a * SR), int(d * SR), int(r * SR)
    na = min(na, n)
    env[:na] = np.linspace(0, 1, na, endpoint=False)
    nd = min(nd, n - na)
    env[na:na + nd] = np.linspace(1, s, nd, endpoint=False)
    nr = min(nr, n)
    if nr > 0:
        env[-nr:] *= np.linspace(1, 0, nr)
    return env


def place(buf, x, start_s, gain=1.0):
    i = int(start_s * SR)
    if i >= buf.shape[-1]:
        return
    j = min(buf.shape[-1], i + x.shape[-1])
    buf[..., i:j] += gain * x[..., :j - i]


def pan(x, p):
    """p in [-1, 1] -> stereo (constant power)."""
    a = (p + 1) * np.pi / 4
    return np.stack([x * np.cos(a), x * np.sin(a)])


def reverb_ir(seconds=2.8, decay=3.2):
    n = int(seconds * SR)
    tt = t_of(n)
    env = np.exp(-decay * tt / seconds * 2.2)
    ir = np.stack([rng.standard_normal(n) * env, rng.standard_normal(n) * env])
    ir = np.stack([lp(ir[0], 6500), lp(ir[1], 6500)])
    ir[:, :int(0.012 * SR)] = 0  # pre-delay
    return ir / np.sqrt((ir ** 2).sum(axis=1, keepdims=True))


IR = reverb_ir()


def wet(x, mix):
    out = np.stack([fftconvolve(x[0], IR[0])[:x.shape[1]], fftconvolve(x[1], IR[1])[:x.shape[1]]])
    return x * (1 - mix) + out * mix * 1.4


# ---------------------------------------------------------------- harmony
# i - VI - III - VII in D minor, one chord per bar. Voicings are MIDI notes.
PROG = [
    [50, 57, 62, 65, 69],   # Dm   (D3 A3 D4 F4 A4)
    [46, 53, 58, 62, 65],   # Bb
    [53, 57, 60, 65, 69],   # F
    [48, 55, 60, 64, 67],   # C
]
ROOTS = [38, 34, 41, 36]    # D2 Bb1 F2 C2


def chord_for(bar):
    return PROG[bar % 4], ROOTS[bar % 4]


# ---------------------------------------------------------------- instruments
def pad_note(m, dur, bright=1800.0):
    n = int(dur * SR)
    f = midi_hz(m)
    v = np.zeros((2, n))
    for k, det in enumerate([-0.11, -0.06, -0.02, 0.0, 0.02, 0.06, 0.11]):
        s = saw(f * 2 ** (det / 12), n, phase=rng.random())
        v += pan(s, (k - 3) / 3.5)
    v /= 7
    env = adsr(n, 0.9, 0.5, 0.8, 1.2)
    v = np.stack([lp(v[0], bright), lp(v[1], bright)]) * env
    return v


def pad_bar(bar, bars=1, gain=0.16, bright=1800.0):
    notes, _ = chord_for(bar)
    dur = BAR * bars + 1.2
    out = np.zeros((2, int(dur * SR)))
    for m in notes:
        out += pad_note(m, dur, bright)
    return out * gain


def drone(dur, m=26, gain=0.25):
    n = int(dur * SR)
    tt = t_of(n)
    f = midi_hz(m)
    x = np.sin(2 * np.pi * f * tt) + 0.35 * np.sin(2 * np.pi * 2 * f * tt + 0.3)
    x *= 1 + 0.15 * np.sin(2 * np.pi * 0.2 * tt)
    return pan(x * adsr(n, 2.0, 0.1, 1.0, 2.0) * gain, 0)


def kick():
    n = int(0.55 * SR)
    tt = t_of(n)
    f = 44 + 110 * np.exp(-tt * 28)
    body = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-tt * 6.5)
    click = hp(rng.standard_normal(n), 2500) * np.exp(-tt * 300) * 0.25
    return pan(np.tanh((body + click) * 1.6) * 0.9, 0)


def snare():
    n = int(0.45 * SR)
    tt = t_of(n)
    noise = bp(rng.standard_normal(n), 900, 7000) * np.exp(-tt * 13)
    tone = np.sin(2 * np.pi * 185 * tt) * np.exp(-tt * 22)
    return pan((noise * 0.55 + tone * 0.45) * 0.7, 0)


def hat(open_=False):
    n = int((0.25 if open_ else 0.07) * SR)
    tt = t_of(n)
    x = hp(rng.standard_normal(n), 7500, 4) * np.exp(-tt * (14 if open_ else 70))
    return x * 0.22


def bass_note(m, dur):
    n = int(dur * SR)
    f = midi_hz(m)
    tt = t_of(n)
    x = np.sin(2 * np.pi * f * tt) + 0.5 * lp(saw(f, n), 380)
    return pan(x * adsr(n, 0.005, 0.12, 0.6, 0.06) * 0.42, 0)


def pluck(m, dur=0.5, p=0.0):
    n = int(dur * SR)
    tt = t_of(n)
    f = midi_hz(m)
    x = 0.6 * saw(f, n) + 0.4 * np.sign(np.sin(2 * np.pi * f * tt))
    cut = 600 + 5200 * np.exp(-tt * 9)
    # time-varying cutoff, approximated in blocks
    y = np.zeros(n)
    blk = 512
    for i in range(0, n, blk):
        y[i:i + blk] = lp(x[i:i + blk], float(cut[i]), 1)
    return pan(y * np.exp(-tt * 6.0) * 0.16, p)


def bell(m, dur=2.2, p=0.0):
    n = int(dur * SR)
    tt = t_of(n)
    f = midi_hz(m)
    x = (np.sin(2 * np.pi * f * tt) + 0.4 * np.sin(2 * np.pi * f * 2.76 * tt) * np.exp(-tt * 3)
         + 0.2 * np.sin(2 * np.pi * f * 5.4 * tt) * np.exp(-tt * 6))
    return pan(x * np.exp(-tt * 1.8) * 0.2, p)


def impact(big=1.0):
    n = int(4.0 * SR)
    tt = t_of(n)
    boom = np.sin(2 * np.pi * np.cumsum(38 + 60 * np.exp(-tt * 9)) / SR) * np.exp(-tt * 1.3)
    crash = lp(rng.standard_normal(n), 5200) * np.exp(-tt * 2.4) * 0.35
    thump = np.tanh(boom * 2.0) * 0.9
    return np.stack([thump + crash, thump + np.roll(crash, 97)]) * 0.75 * big


def riser(dur):
    n = int(dur * SR)
    tt = t_of(n)
    prog = (tt / dur) ** 2
    noise = rng.standard_normal(n)
    y = np.zeros(n)
    blk = 1024
    for i in range(0, n, blk):
        c = 300 + 7000 * prog[i]
        y[i:i + blk] = bp(noise[i:i + blk], c * 0.7, min(c * 1.3, SR / 2 - 100), 1)
    tone = np.sin(2 * np.pi * np.cumsum(200 + 900 * prog) / SR) * 0.15
    x = (y * 0.5 + tone) * prog
    return np.stack([x, np.roll(x, 211)]) * 0.5


def swell(dur):
    """A reversed pad: grows into the downbeat after it."""
    notes, _ = chord_for(0)
    v = np.zeros((2, int(dur * SR)))
    for m in notes:
        v += pad_note(m + 12, dur, 3200)[:, :v.shape[1]]
    env = np.linspace(0, 1, v.shape[1]) ** 3
    return v * env * 0.2


# ---------------------------------------------------------------- arrangement
music = np.zeros((2, N))
drums = np.zeros((2, N))
duck = np.ones(N)


def bar_t(b, beat=0.0):
    return b * BAR + beat * BEAT


# Pads: every bar except the drop-out before the final hit.
for b in range(BARS):
    bright = 1300 if b < 4 else (2400 if b < 21 else 1600)
    gain = 0.13 if b < 4 else (0.11 if b < 21 else 0.14)
    if b == 22:
        gain *= 0.8
    place(music, pad_bar(b, 1, gain, bright), bar_t(b))

# Low drone under the cold open and the logo.
place(music, drone(BAR * 4 + 1.0), 0.0)
place(music, swell(BAR * 2), 0.0, 0.8)

# Impacts: the logo, the drop, the end card.
place(music, impact(0.9), bar_t(2))
place(music, impact(0.7), bar_t(4))
place(music, impact(1.0), bar_t(23))

# Risers into the drop, into the map lift, into the end card.
place(music, riser(BAR * 2), bar_t(2))
place(music, riser(BAR * 1), bar_t(18))
place(music, riser(BAR * 2), bar_t(21))

# Drums bars 4-20.
for b in range(4, 21):
    for beat in (0, 2):
        place(drums, kick(), bar_t(b, beat))
        i = int(bar_t(b, beat) * SR)
        k = int(0.32 * SR)
        duck[i:i + k] = np.minimum(duck[i:i + k], 0.35 + 0.65 * np.linspace(0, 1, k) ** 0.6)
    if b >= 6:
        place(drums, snare(), bar_t(b, 1))
        place(drums, snare(), bar_t(b, 3))
    for e in range(8):
        h = hat(open_=(e % 4 == 2 and b >= 8))
        place(drums, pan(h, 0.35 if e % 2 else -0.25), bar_t(b, e / 2), 0.9 if e % 2 else 0.6)
    if b in (11, 15, 19):  # fills
        for s in range(4):
            place(drums, snare(), bar_t(b, 3 + s / 4), 0.35 + 0.15 * s)

# Pulse bass: eighths on the root, bars 4-20.
for b in range(4, 21):
    _, root = chord_for(b)
    for e in range(8):
        m = root + (12 if e in (3, 7) else 0)
        place(music, bass_note(m, BEAT / 2 * 0.95), bar_t(b, e / 2))

# Arp: sixteenths through the chord, bars 8-20, with a ping-pong delay.
arp = np.zeros((2, N))
for b in range(8, 21):
    notes, _ = chord_for(b)
    pat = [notes[1] + 12, notes[2] + 12, notes[3] + 12, notes[4] + 12,
           notes[3] + 12, notes[2] + 12, notes[4] + 12, notes[2] + 24]
    for s in range(16):
        place(arp, pluck(pat[s % 8], 0.4, -0.3 if s % 2 else 0.3), bar_t(b, s / 4))
d = int(BEAT * 0.75 * SR)
echo = np.zeros_like(arp)
echo[0, d:] = arp[1, :-d] * 0.38
echo[1, 2 * d:] = arp[0, :-2 * d] * 0.25
music += arp + echo

# Breakdown bell line, bars 21-22 and over the end card.
line = [(21, 0, 74), (21, 1.5, 77), (21, 3, 76), (22, 0, 74), (22, 1.5, 72), (22, 3, 69),
        (23, 0, 74), (23, 2, 81)]
for b, beat, m in line:
    place(music, bell(m, 2.6, 0.2 if m % 2 else -0.2), bar_t(b, beat))

# Final held chord, Dm(add9), over the end card.
final = np.zeros((2, int((BAR * 2 + TAIL) * SR)))
for m in [38, 50, 57, 62, 64, 65, 69, 76]:
    final += pad_note(m, BAR * 2 + TAIL, 2600)[:, :final.shape[1]]
place(music, final * 0.13, bar_t(23))

# ---------------------------------------------------------------- mix
music = music * duck  # sidechain the melodic bed to the kick
mix = wet(music, 0.32) + wet(drums, 0.10)
mix = hp(mix, 28)

# Master: gentle glue, soft clip, fade the tail, normalise to -1 dBFS.
mix = np.tanh(mix * 1.25) / np.tanh(1.25)
fade = int(TAIL * SR)
mix[:, -fade:] *= np.linspace(1, 0, fade) ** 1.5
mix[:, :int(0.02 * SR)] *= np.linspace(0, 1, int(0.02 * SR))
mix *= 10 ** (-1 / 20) / np.max(np.abs(mix))

out = sys.argv[1] if len(sys.argv) > 1 else 'score.wav'
pcm = (mix.T * 32767).astype('<i2')
import wave
with wave.open(out, 'wb') as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(SR)
    w.writeframes(pcm.tobytes())
print(f'wrote {out}: {N / SR:.2f}s, bar {BAR:.3f}s')
