using System.Reflection;
using System.Text.Json;

namespace EQBuddy.Core;

/// <summary>Buff landing lines ("You feel the favor of the gods upon you.") mapped to
/// candidate spells with wiki durations — the catalog behind buff countdown timers.
/// Generated by scripts/harvests/eqlwiki/buffs-harvest.py.</summary>
public sealed class BuffDurationCatalog
{
    public sealed class BuffSpell
    {
        public string Name { get; set; } = "";
        public double DurationSeconds { get; set; }
    }

    public sealed class Entry
    {
        public string Message { get; set; } = "";
        public string Label { get; set; } = "";
        public BuffSpell[] Spells { get; set; } = [];
    }

    private sealed class Root { public List<Entry> Messages { get; set; } = []; }

    private readonly Dictionary<string, Entry> _byMessage;
    private readonly HashSet<string> _spellNames;

    public BuffDurationCatalog(IEnumerable<Entry> entries)
    {
        _byMessage = entries.Where(e => e.Message.Length > 0 && e.Spells.Length > 0)
            .ToDictionary(e => e.Message, e => e, StringComparer.OrdinalIgnoreCase);
        _spellNames = _byMessage.Values.SelectMany(e => e.Spells.Select(s => s.Name))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    public int Count => _byMessage.Count;
    public Entry? Find(string message) => _byMessage.TryGetValue(message, out var e) ? e : null;
    public bool IsBuffSpell(string spell) => _spellNames.Contains(SpellCatalog.BaseName(spell));

    /// <summary>Every spell whose landing line the catalog can attribute — the buff-set
    /// editor's search space (#120). Restricting set entries to these keeps the set
    /// honest: a spell whose landing we can't recognize would read "not seen" forever.</summary>
    public IReadOnlyCollection<string> SpellNames => _spellNames;

    private static readonly JsonSerializerOptions JsonOpts = new() { PropertyNameCaseInsensitive = true };

    public static BuffDurationCatalog LoadEmbedded()
    {
        using var stream = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream("EQBuddy.Core.Data.BuffDurations.json")
            ?? throw new InvalidOperationException("BuffDurations.json missing from resources");
        var root = JsonSerializer.Deserialize<Root>(stream, JsonOpts)
            ?? throw new InvalidOperationException("BuffDurations.json unreadable");
        return new BuffDurationCatalog(root.Messages);
    }

    public static BuffDurationCatalog Default { get; } = LoadEmbedded();
}

/// <summary>A buff currently believed active on YOU. Estimated means the duration is
/// the wiki base for an unresolved candidate set (or the longest of them) — ranks and
/// AAs lengthen buffs, so the countdown is labeled est until a natural fade teaches
/// the character's real number.</summary>
public sealed record BuffState(
    string Label, string[] Candidates, string Caster,
    DateTime LandedAt, DateTime? ExpiresAt, bool Estimated)
{
    public double? RemainingSeconds(DateTime now) =>
        ExpiresAt is { } e ? Math.Max(0, (e - now).TotalSeconds) : null;

    /// <summary>
    /// The landing's FULL candidate set, kept only when a `/outputfile spellbook` dump
    /// narrowed <see cref="Candidates"/> — empty otherwise, which is every buff the log
    /// alone accounted for.
    ///
    /// **One property rather than three, on purpose.** It answers "did the dump decide
    /// this" (<see cref="DumpNarrowed"/>) and "what may a fade line call it"
    /// (<see cref="FadeNames"/>) from a single stored fact; two fields agreeing about one
    /// event is trap 4, and these two questions are only ever asked together.
    /// </summary>
    public string[] NarrowedFrom { get; init; } = [];

    /// <summary>A spellbook dump — not the log — decided which candidates stand. Blocks
    /// fade-teaching: <see cref="BuffTracker"/> learns a real duration only from a landing
    /// the LOG resolved, and a dump-narrowed set of one is not that. Without this gate the
    /// spellbook would become a timer source through the back door, which is exactly the
    /// thing the owner lock rules out.</summary>
    public bool DumpNarrowed => NarrowedFrom.Length > 0;

    /// <summary>Every name a fade line may use for this buff. **The dump must never cost
    /// us a fade**: narrowing to "Rune V" and then meeting a "Rune IV" fade line would
    /// leave the chip hanging until its linger expired, which is a stale spellbook
    /// erasing something the log plainly said. Fades match the wider set; only the
    /// countdown and the tooltip use the narrower one.</summary>
    public string[] FadeNames => DumpNarrowed ? NarrowedFrom : Candidates;

    /// <summary>
    /// The EXACT ranked name the cast line used - "Shield of Thorns V" where
    /// <see cref="Label"/> is the rank-folded "Shield of Thorns". Empty when the log named
    /// no caster, which is every landing the log alone could not attribute.
    ///
    /// **Kept because the rank decides the LENGTH.** The fold is right for identity (one
    /// Shield of Thorns is up on you, whichever rank it is) and wrong for duration - ranks
    /// lengthen buffs, and throwing the rank away while looking up a duration is looking up
    /// rank I's number for a rank V cast. <see cref="RankedBuffDurationLedger"/> and the
    /// learned-duration store are both keyed on this, not on <see cref="Label"/>.
    /// </summary>
    public string Spell { get; init; } = "";

    /// <summary>
    /// <see cref="Spell"/> came from the player's OWN last cast of this line, not from a cast
    /// line for this landing - a Quick Buff landing, which names nothing (DRA-339). The rank is
    /// what the log last showed you casting, which is the best evidence there is and still an
    /// inference, so it blocks fade-teaching exactly as <see cref="DumpNarrowed"/> does: a
    /// learned duration is keyed on a rank the LOG named for that landing, or it is not learned.
    /// </summary>
    public bool RankInferred { get; init; }

    /// <summary>
    /// The length EQBuddy worked out on its own - learned, measured or catalog, with SCR -
    /// before any length the player typed (#954). Kept so "use EQBuddy's length" can put the
    /// countdown back without re-reading the landing, and so the editor can show both numbers.
    /// </summary>
    public double DerivedSeconds { get; init; }

    /// <summary>Whether <see cref="DerivedSeconds"/> was an estimate - what
    /// <see cref="Estimated"/> goes back to when the player's length is cleared.</summary>
    public bool DerivedEstimated { get; init; }

    /// <summary>The countdown is running on a length the PLAYER typed (#954), which outranks
    /// everything EQBuddy derives, the spawn-timer override rule. Not an estimate: the chip
    /// drops "est", and the hover says whose number it is.</summary>
    public bool PlayerSet { get; init; }

    /// <summary>
    /// What a player-typed length is filed under: the RANKED name when the log named one,
    /// else the label. Ranked, because a length typed for Shield of Thorns IV is not V's
    /// (trap 71 - the fold is right for identity and wrong for a quantity); the label for a
    /// landing nobody attributed, which is the only name the chip ever showed for it.
    /// </summary>
    public string DurationKey => Spell.Length > 0 ? Spell : Label;
}

/// <summary>
/// Tracks beneficial buffs on the player, the same consumer shape as
/// <see cref="MezTracker"/>: cast lines arm a short window, the cast-on-you line
/// inside it starts the countdown, the fade line ends it — and a natural fade whose
/// landing was cleanly attributed teaches the spell's REAL duration for this
/// character (ranks and AAs lengthen buffs; the wiki base is a floor, so learned
/// values only ever ratchet the countdown up, tick-floored). Zoning keeps buffs —
/// they survive it in game; dying does not.
/// </summary>
public sealed class BuffTracker
{
    public static readonly TimeSpan CastToLand = TimeSpan.FromSeconds(8);
    /// <summary>Past its expiry a chip lingers at 0:00 — an estimated duration is a
    /// floor (ranks lengthen), so vanishing exactly on time would often be a lie.
    /// The fade line is the real end and clears it whenever it comes.</summary>
    public static readonly TimeSpan ExpiryLinger = TimeSpan.FromMinutes(5);
    public const double ServerTickSeconds = 6;

    private readonly BuffDurationCatalog _catalog;
    private readonly Dictionary<string, double> _learned = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, BuffState> _active = new(StringComparer.OrdinalIgnoreCase);
    // Session-seen evidence behind the buff set's honesty states (#120). These answer
    // "did THIS session's log ever show it", not "is it up" — so death and zoning
    // never clear them, and an unresolved landing marks its WHOLE candidate set seen
    // (the same identity treatment the tracker gives the active entry itself).
    private readonly HashSet<string> _seenLandings = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _seenFades = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _seenOwnCasts = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<(string Caster, string Spell, DateTime Time)> _recentCasts = [];
    private readonly Dictionary<string, DateTime> _lastCastOf = new(StringComparer.OrdinalIgnoreCase);
    // The RANKED name of YOUR last cast of each line, keyed on the folded name - what a
    // Quick Buff landing (which names no spell) is resolved to (DRA-339). Session evidence:
    // the launch replay re-reads the log, so it is rebuilt with everything else.
    private readonly Dictionary<string, (string Ranked, DateTime Time)> _ownRankOf =
        new(StringComparer.OrdinalIgnoreCase);
    private DateTime? _quickBuffAt;
    private string? _storePath;
    private readonly object _lock = new();

    public event Action? Changed;

    /// <summary>The player's Spell Casting Reinforcement rank (0–4), from the AA
    /// ledger: +5/15/30/50% duration on beneficial spells YOU cast. Applied to the
    /// wiki-base estimate only — a learned duration already includes the character's
    /// real extensions, and applying it twice would overshoot every countdown.</summary>
    public Func<int>? ReinforcementRank { get; set; }

    private readonly RankedBuffDurationLedger _ranked;

    public BuffTracker(BuffDurationCatalog? catalog = null, RankedBuffDurationLedger? ranked = null)
    {
        _catalog = catalog ?? BuffDurationCatalog.Default;
        _ranked = ranked ?? RankedBuffDurationLedger.Default;
    }

    // ---- the optional spellbook (OE-5 LOCK A) -----------------------------------

    private SpellbookFile.Snapshot? _spellbook;
    private string? _spellbookFolder;
    private string _spellbookCharacter = "";

    /// <summary>
    /// Point the tracker at this character's `/outputfile spellbook` dump, if there is
    /// one. Optional in every sense: a character who has never run the command, a folder
    /// that does not exist and an unreadable file all leave the tracker doing exactly what
    /// it did before this existed.
    ///
    /// <see cref="LogWatcher.Select"/> calls it, because Select is the one place that
    /// knows both the log folder and the character — the same moment it resets the
    /// session for the newly selected log. The folder and character are remembered so a
    /// `/outputfile spellbook` run mid-session can re-read on its own announcement.
    /// </summary>
    public void AttachSpellbook(string? logFolder, string character)
    {
        _spellbookFolder = logFolder;
        _spellbookCharacter = character ?? "";
        ReloadSpellbook();
    }

    /// <summary>What the attached dump said, or null when there is none. For tests and for
    /// anything that wants to report the dump's age; nothing in the tracker's own path
    /// needs it.</summary>
    public SpellbookFile.Snapshot? Spellbook
    {
        get { lock (_lock) return _spellbook; }
    }

    /// <summary>Read the dump for the attached character. File I/O deliberately OUTSIDE
    /// the lock — the ingest thread calls this from <see cref="Apply"/> when a dump is
    /// announced, and a slow disk must not stall a landing.</summary>
    private void ReloadSpellbook()
    {
        if (_spellbookCharacter.Length == 0) { lock (_lock) _spellbook = null; return; }
        var book = SpellbookFile.FindLatest(_spellbookFolder, _spellbookCharacter);
        lock (_lock) _spellbook = book;
    }

    /// <summary>Learned durations persist per character (mez-store pattern).</summary>
    public void AttachStore(string path)
    {
        _storePath = path;
        try
        {
            // ProfileJson, so a file killed mid-write falls back to the previous good copy.
            ProfileJson.Read<Dictionary<string, double>>(path, null, out var stored);
            if (stored is null) return;
            lock (_lock)
                foreach (var (spell, seconds) in stored)
                    if (seconds is > 0 and < 4 * 3600) _learned.TryAdd(spell, seconds);
        }
        catch { /* corrupt store: rewritten on next learn */ }
    }

    public void Apply(GameEvent evt)
    {
        // The dump's own announcement, read here on the ingest thread the same way the
        // quest reconcile reads the inventory one (#241): running /outputfile spellbook
        // mid-session sharpens the NEXT landing rather than the next launch. Outside the
        // lock, because it is file I/O and it opens no buff state.
        if (evt is OutputfileEvent dump
            && OutputfileAutoImport.KindOf(dump.FileName) == OutputfileKind.Spellbook)
            ReloadSpellbook();

        var changed = false;
        lock (_lock)
        {
            switch (evt)
            {
                case SpellCastEvent own when _catalog.IsBuffSpell(own.Spell):
                    Remember("You", own.Spell, own.Time);
                    _seenOwnCasts.Add(SpellCatalog.BaseName(own.Spell));
                    _ownRankOf[SpellCatalog.BaseName(own.Spell)] = (own.Spell.Trim(), own.Time);
                    break;
                case QuickBuffEvent quick:
                    _quickBuffAt = quick.Time;
                    break;
                case OtherCastEvent other when _catalog.IsBuffSpell(other.Spell):
                    Remember(other.Caster, other.Spell, other.Time);
                    break;

                case BuffLandedEvent landed when _catalog.Find(landed.Message) is { } entry:
                    changed = OnLanding(entry, landed.Time);
                    break;

                // A blocked cast never lands, so no state opens (landing lines are the
                // only thing that opens state) — but its cast must not stay remembered:
                // armed for up to CastToLand, it would resolve a LATER unexplained
                // landing of the same message (a groupmate's cast, a clicky) to OUR
                // cast and caster. Only "You" disarms — the line is first-person.
                case SpellBlockedEvent blocked:
                    _recentCasts.RemoveAll(c => c.Caster == "You"
                        && SpellCatalog.BaseName(c.Spell).Equals(
                            SpellCatalog.BaseName(blocked.Spell), StringComparison.OrdinalIgnoreCase));
                    break;

                case BuffFadeEvent fade:
                    // Even a fade with no active match is evidence (#120): the log
                    // opened mid-session, the buff WAS up, and now it's gone.
                    foreach (var s in fade.Spells.Where(_catalog.IsBuffSpell))
                        _seenFades.Add(SpellCatalog.BaseName(s));
                    changed = OnFade(fade.Spells, fade.Time);
                    break;
                // "Your X spell has worn off." with no target names YOUR buff ending.
                case SpellWornOffEvent { Pet: false, Target.Length: 0 } worn
                    when _catalog.IsBuffSpell(worn.Spell):
                    _seenFades.Add(SpellCatalog.BaseName(worn.Spell));
                    changed = OnFade([worn.Spell], worn.Time);
                    break;

                case DeathEvent:
                    changed = _active.Count > 0;
                    _active.Clear();
                    break;
                    // ZoneEvent deliberately absent: buffs survive zoning.
            }
            _recentCasts.RemoveAll(c => evt.Time - c.Time > CastToLand);
            foreach (var (key, b) in _active.Where(kv =>
                         kv.Value.ExpiresAt is { } e && evt.Time - e > ExpiryLinger).ToList())
            {
                _active.Remove(key);
                changed = true;
            }
        }
        if (changed) Changed?.Invoke();
    }

    private void Remember(string caster, string spell, DateTime t)
    {
        _recentCasts.Add((caster, spell, t));
        if (_recentCasts.Count > 32) _recentCasts.RemoveRange(0, 16);
        _lastCastOf[SpellCatalog.BaseName(spell)] = t;
    }

    private bool OnLanding(BuffDurationCatalog.Entry entry, DateTime time)
    {
        // A recent cast of a candidate names the spell exactly (and its caster);
        // without one — a clicky, a stranger out of range — every candidate stands,
        // the longest duration wins, and the chip says est.
        var cast = _recentCasts.LastOrDefault(c => time - c.Time <= CastToLand
            && entry.Spells.Any(s => s.Name.Equals(SpellCatalog.BaseName(c.Spell), StringComparison.OrdinalIgnoreCase)));
        var rankInferred = false;
        // QUICK BUFF (DRA-339). EQL's rebuff button casts YOUR buffs and prints no cast line for
        // any of them, so every landing after it used to fall to the unresolved branch below:
        // rank I's wiki base, no Spell Casting Reinforcement, never the ranked ledger. The
        // owner's Shield of Thorns V armed at 900 s against the 1,416 s it runs - the chicklet
        // up with nine and a half minutes still on the shield, from the button he rebuffs with
        // (199 activations in his log). A cast line still wins; this speaks only where none did,
        // and only in a candidate YOU have been seen casting, at the rank you last cast it.
        if (cast.Spell is not { Length: > 0 }
            && _quickBuffAt is { } quick && time >= quick && time - quick <= CastToLand
            && entry.Spells
                .Where(s => _ownRankOf.ContainsKey(s.Name))
                .Select(s => _ownRankOf[s.Name])
                .OrderByDescending(o => o.Time)
                .FirstOrDefault() is { Ranked.Length: > 0 } own)
        {
            cast = ("You", own.Ranked, quick);
            rankInferred = true;
        }
        var resolved = cast.Spell is { Length: > 0 };
        var label = resolved ? SpellCatalog.BaseName(cast.Spell) : entry.Label;
        var candidates = resolved ? new[] { label } : entry.Spells.Select(s => s.Name).ToArray();

        // THE DUMP ONLY EVER SPEAKS WHERE THE LOG DID NOT. A cast line names the spell and
        // its caster outright, so a resolved landing is untouched here — including one the
        // spellbook does not list, which is a stale dump and not a wrong log.
        var narrowedFrom = Array.Empty<string>();
        if (!resolved && NarrowBySpellbook(candidates) is { } narrowed)
        {
            narrowedFrom = candidates;
            candidates = narrowed;
        }

        // The RANKED name, kept whole. The catalog lookup below still folds it - eqlwiki
        // holds one page per spell line - but the rank is what decides the LENGTH, so
        // everything that answers "how long" is keyed on this instead.
        var ranked = resolved ? cast.Spell.Trim() : "";

        // A MEASURED length for this exact rank beats the wiki's rank-I number. This is
        // the whole fix: "Shield of Thorns V" is 1,350 s base where the folded page says
        // 900, so every surface armed off the folded number fired nearly eight minutes
        // early. A rank nobody has measured is absent from the ledger and falls straight
        // through to the wiki base, exactly as before.
        var baseSeconds = _ranked.BaseSeconds(ranked)
            ?? (resolved
                ? entry.Spells.First(s => s.Name.Equals(label, StringComparison.OrdinalIgnoreCase)).DurationSeconds
                // The longest of what is STILL standing. Narrowing "Rune IV or Rune V" down to
                // the rank this character has scribed is the whole accuracy win: the estimate
                // stops being the longest rank in the game and becomes the longest rank you own.
                : entry.Spells.Where(s => candidates.Contains(s.Name, StringComparer.OrdinalIgnoreCase))
                    .Max(s => s.DurationSeconds));
        // Your own cast gets your Spell Casting Reinforcement applied to the estimate;
        // someone else's caster AAs are invisible to your log, so their base stands. ONE
        // application, of the rank the AA ledger reports and no other - the ledger above
        // stores pre-AA lengths precisely so this can stay the only place SCR is spent.
        if (resolved && cast.Caster == "You")
            baseSeconds = BuffDurationModel.WithReinforcement(
                baseSeconds, ReinforcementRank?.Invoke() ?? 0);

        // Learned beats measured-elsewhere: a fade this character's own log timed is the
        // only number that already carries THEIR ranks and THEIR AAs. Ranked key first,
        // because a duration learned at rank II is not this rank's duration; the folded key
        // is the fallback that keeps every value learned before ranks were keyed at all.
        var learned = resolved ? LearnedFor(ranked, label) : null;
        var estimated = !resolved || learned is null;
        var derived = learned ?? baseSeconds;

        // The sights are the LOG's claim about what this session showed (#120's honesty
        // states), so they mark the whole landing — a dump that narrowed the countdown has
        // not made the other candidates un-seen. Marked BEFORE the dismissal check below: a
        // landing the player dismissed still happened.
        _seenLandings.Add(SpellCatalog.BaseName(label));
        foreach (var c in narrowedFrom.Length > 0 ? narrowedFrom : candidates)
            _seenLandings.Add(SpellCatalog.BaseName(c));

        // DISMISSED (#954). The launch replay re-reads the whole log, so a dismissal held in
        // RAM would bring the chip straight back on the next start - trap 85's exact shape.
        // The gate is the landing's own LOG time, persisted: this landing and anything older
        // stay gone, and the next real landing of the buff shows normally.
        if (_dismissed.TryGetValue(PlayerKey(label), out var dismissedAt) && time <= dismissedAt)
            return false;

        var state = new BuffState(label, candidates, resolved ? cast.Caster : "",
            time, time.AddSeconds(derived), estimated)
        {
            NarrowedFrom = narrowedFrom,
            Spell = ranked,
            RankInferred = rankInferred,
            DerivedSeconds = derived,
            DerivedEstimated = estimated,
        };
        _active[label] = WithPlayerLength(state);
        return true;
    }

    // ---- the player's own word: dismiss, and a typed length (#954) ----------------

    // Both keyed "character|name", because both are statements about ONE character's buffs:
    // a length typed on a character with Spell Casting Reinforcement is not another's, and a
    // dismissal on A must not swallow B's landing that happens to be older.
    private readonly Dictionary<string, double> _playerLengths = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, DateTime> _dismissed = new(StringComparer.OrdinalIgnoreCase);
    private string? _playerStorePath;

    private sealed class PlayerStore
    {
        public Dictionary<string, double> Lengths { get; set; } = [];
        public Dictionary<string, DateTime> Dismissed { get; set; } = [];
    }

    private string PlayerKey(string name) => _spellbookCharacter + "|" + name;

    /// <summary>The player's typed lengths and dismissals persist (#954) — both have to
    /// survive the launch replay, or the replay undoes them.</summary>
    public void AttachPlayerStore(string path)
    {
        _playerStorePath = path;
        try
        {
            ProfileJson.Read<PlayerStore>(path, null, out var stored);
            if (stored is null) return;
            lock (_lock)
            {
                foreach (var (key, seconds) in stored.Lengths)
                    if (seconds > 0 && seconds < MaxPlayerSeconds) _playerLengths.TryAdd(key, seconds);
                foreach (var (key, at) in stored.Dismissed) _dismissed.TryAdd(key, at);
            }
        }
        catch { /* corrupt store: rewritten on the next dismissal or typed length */ }
    }

    /// <summary>Longest length a player may type. Generous (a day) on purpose — it exists to
    /// refuse garbage, not to second-guess a real buff.</summary>
    public const double MaxPlayerSeconds = 24 * 3600;

    /// <summary>
    /// Right-click on a buff chip (#954, charlesneitzel): drop this buff now. Held against
    /// the landing's LOG time, so it outlives the replay the next launch does, and the next
    /// real landing of the buff starts a fresh chip — the slow-chip rule, made durable.
    /// </summary>
    public void Dismiss(string label)
    {
        bool changed;
        lock (_lock)
        {
            changed = _active.Remove(label, out var gone);
            if (changed) _dismissed[PlayerKey(label)] = gone!.LandedAt;
        }
        if (!changed) return;
        SavePlayerStore();
        Changed?.Invoke();
    }

    /// <summary>
    /// The length the player typed for this buff, or null when they have not (#954). Keyed
    /// on <see cref="BuffState.DurationKey"/>.
    /// </summary>
    public double? PlayerLengthFor(string durationKey)
    {
        lock (_lock)
            return _playerLengths.TryGetValue(PlayerKey(durationKey), out var s) ? s : null;
    }

    /// <summary>
    /// Set (or, with null, clear) the player's own length for a buff, and re-derive any
    /// running countdown from its ORIGINAL landing — the spawn-timer override rule. Typed
    /// by the player, so it outranks learned, measured and catalog lengths alike, until they
    /// clear it. Returns false for a length outside (0, <see cref="MaxPlayerSeconds"/>).
    /// </summary>
    public bool SetPlayerLength(string durationKey, double? seconds)
    {
        if (seconds is { } s && (!double.IsFinite(s) || s <= 0 || s >= MaxPlayerSeconds)) return false;
        lock (_lock)
        {
            if (seconds is { } set) _playerLengths[PlayerKey(durationKey)] = set;
            else _playerLengths.Remove(PlayerKey(durationKey));
            foreach (var (label, b) in _active.ToList())
                if (b.DurationKey.Equals(durationKey, StringComparison.OrdinalIgnoreCase))
                    _active[label] = WithPlayerLength(b);
        }
        SavePlayerStore();
        Changed?.Invoke();
        return true;
    }

    /// <summary>The state with the player's length applied, or with EQBuddy's own put back
    /// when there is none. Callers hold _lock.</summary>
    private BuffState WithPlayerLength(BuffState b) =>
        _playerLengths.TryGetValue(PlayerKey(b.DurationKey), out var typed)
            ? b with { ExpiresAt = b.LandedAt.AddSeconds(typed), Estimated = false, PlayerSet = true }
            : b with
            {
                ExpiresAt = b.LandedAt.AddSeconds(b.DerivedSeconds),
                Estimated = b.DerivedEstimated,
                PlayerSet = false,
            };

    /// <summary>Player actions are rare and made on the UI thread; written at once, outside
    /// the lock, through ProfileJson so a kill mid-write keeps the previous copy.</summary>
    private void SavePlayerStore()
    {
        if (_playerStorePath is not { } path) return;
        try
        {
            string json;
            lock (_lock)
                json = JsonSerializer.Serialize(new PlayerStore
                {
                    Lengths = new(_playerLengths, StringComparer.OrdinalIgnoreCase),
                    Dismissed = new(_dismissed, StringComparer.OrdinalIgnoreCase),
                });
            ProfileJson.Write(path, json);
        }
        catch { /* best-effort */ }
    }

    /// <summary>
    /// What this character's own log has timed for this spell: the exact ranked name first,
    /// the rank-folded name second, null when neither has been seen.
    ///
    /// **Two keys because the store predates the rank.** New learns are written under the
    /// ranked name (<see cref="OnFade"/>) - a duration measured at rank II is not rank V's
    /// duration, and one key for both is the same conflation that made the wiki base wrong
    /// here in the first place. Every value learned before that is keyed on the folded name,
    /// and dropping it would silently throw away a real measurement to fix a rarer one, so
    /// it stays as the fallback. Unranked spells resolve to the same string twice and are
    /// unaffected either way. Callers hold _lock.
    /// </summary>
    private double? LearnedFor(string ranked, string label)
    {
        if (ranked.Length > 0 && _learned.TryGetValue(ranked, out var exact)) return exact;
        return _learned.TryGetValue(label, out var folded) ? folded : null;
    }

    /// <summary>
    /// The candidates this character has actually scribed, or null when the dump narrows
    /// nothing — no spellbook attached, or one that recognises none of them.
    ///
    /// **A dump that knows none of the candidates narrows NOTHING, and that is the load
    /// bearing line.** A spellbook written before the character learned the spell, a
    /// clicky item, a rank spelled some way this dump does not use — every one of those is
    /// a reason the log is right and the dump is behind, and none of them is a reason to
    /// shrink a landing the log observed. Returning the whole set unchanged is what "the
    /// log outranks the dump" means in code.
    ///
    /// Two tiers, in this order. **Exact** first, because that is the match that buys a
    /// per-rank duration — `BuffDurations.json` carries "Rune IV" at 5,400s beside "Rune V"
    /// at 6,600s. **Line** (rank-folded) second, so a dump that writes its ranks in a shape
    /// we have not seen still separates two DIFFERENT spells sharing one landing message
    /// (Boon of the Clear Mind vs Clarity) instead of giving up.
    /// </summary>
    private string[]? NarrowBySpellbook(string[] candidates)
    {
        if (candidates.Length < 2) return null;
        // A candidate the dump could never have MATCHED is not evidence about the
        // character, and dropping it is the dump overruling the log on a catalog defect.
        // `exact.Length > 0` below reads as "the dump recognised these names"; that was
        // only ever true while every candidate WAS a name a spellbook can carry, and a
        // wiki page title is not (see SpellCatalog.IsLogWritableName). Measured on the
        // owner's real dump in PR #407: it knows five of the six thorns candidates, so it
        // narrowed to those five and dropped `Shield of Thorns (Spell)` — the only one he
        // casts — because his book says "Shield of Thorns" and no book says "(Spell)".
        //
        // So a partially-matching set narrows NOTHING. This is trap 64's shape (a gate
        // written as a proxy stops being that proxy when a second producer arrives) and
        // trap 49's fix (name the fact, not a length). The format guard keeps the shipped
        // catalogs clean; this keeps a future one from silently costing a spell.
        if (Array.Exists(candidates, c => !SpellCatalog.IsLogWritableName(c))) return null;
        SpellbookFile.Snapshot? book;
        lock (_lock) book = _spellbook;
        if (book is null) return null;

        var exact = candidates.Where(book.Knows).ToArray();
        if (exact.Length > 0) return exact.Length < candidates.Length ? exact : null;
        var line = candidates.Where(book.KnowsLine).ToArray();
        return line.Length > 0 && line.Length < candidates.Length ? line : null;
    }

    private bool OnFade(string[] spells, DateTime time)
    {
        // FadeNames, not Candidates: where a spellbook narrowed the set, the fade line may
        // still name a candidate the dump ruled out, and dropping the match would leave a
        // chip hanging that the log had plainly ended. The dump never costs us a fade.
        var doomed = _active.Values.Where(b =>
            b.FadeNames.Intersect(spells, StringComparer.OrdinalIgnoreCase).Any()).ToList();
        foreach (var b in doomed)
        {
            _active.Remove(b.Label);
            // Learning (mez rules, buff flavor): only a cleanly resolved single-spell
            // landing measures anything; a re-cast since landing means this fade may
            // span a chain; and ranks only LENGTHEN, so an observation short of the
            // current belief is a dispel or a click-off, not a duration.
            //
            // `DumpNarrowed` is the second half of that first clause, and it is the gate
            // that keeps the spellbook out of the timer. A set of one used to mean "the
            // LOG named this spell"; a dump can now produce one too, and teaching a real
            // per-character duration off a dump-guessed identity is precisely the
            // back-door the owner lock forbids. Learned durations stay log-taught.
            // RankInferred is the same gate for Quick Buff (DRA-339): the rank came from your
            // LAST cast, not from this landing, and teaching it would file the length of
            // whatever Quick Buff really cast under a rank the log never named for it.
            if (b.Candidates.Length != 1 || b.DumpNarrowed || b.RankInferred) continue;
            var spell = b.Candidates[0];
            if (_lastCastOf.TryGetValue(spell, out var lastCast) && lastCast > b.LandedAt.AddSeconds(1))
                continue;
            // Keyed on the RANKED name the cast used, so upgrading Shield of Thorns IV to V
            // does not inherit IV's length and start the alert early all over again. Falls
            // back to the folded name only where the log named no rank to key on.
            var key = b.Spell.Length > 0 ? b.Spell : spell;
            var observed = Math.Floor((time - b.LandedAt).TotalSeconds / ServerTickSeconds) * ServerTickSeconds;
            var floor = b.ExpiresAt is { } e ? (e - b.LandedAt).TotalSeconds : 0;
            if (observed >= floor && observed is > 30 and < 4 * 3600
                && (!_learned.TryGetValue(key, out var known) || Math.Abs(observed - known) > 0.5))
            {
                _learned[key] = observed;
                SaveStore();
            }
        }
        return doomed.Count > 0;
    }

    /// <summary>Cheap count for headers and per-tick gates — no list, no sort.</summary>
    public int ActiveCount
    {
        get { lock (_lock) return _active.Count; }
    }

    /// <summary>Active buffs, soonest to fade first; expired entries hold at 0:00
    /// until their fade line or the linger cap (estimates are floors, not facts).</summary>
    public List<BuffState> Snapshot(DateTime now)
    {
        lock (_lock)
            return _active.Values
                .OrderBy(b => b.ExpiresAt ?? DateTime.MaxValue)
                .ToList();
    }

    public IReadOnlyDictionary<string, double> LearnedDurations
    {
        get { lock (_lock) return new Dictionary<string, double>(_learned); }
    }

    /// <summary>What this session's log has shown about buff identities, for the buff
    /// set's honesty states (#120): spells seen landing on you (a landing's whole
    /// candidate set counts), spells seen fading (with or without a matching landing),
    /// and buff spells YOU were seen casting (the set editor's seen-first ranking).
    /// Copies — safe to hold across the tracker's own updates.</summary>
    public BuffSetSights SetSights()
    {
        lock (_lock)
            return new BuffSetSights(
                new HashSet<string>(_seenLandings, StringComparer.OrdinalIgnoreCase),
                new HashSet<string>(_seenFades, StringComparer.OrdinalIgnoreCase),
                new HashSet<string>(_seenOwnCasts, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>Log-switch reset (stage 2's fix for a stage-1 flag): active buffs and
    /// session sights were process-lifetime, so character A's landings leaked into
    /// character B's Missing/NotSeen claims after a switch. LogWatcher.Select calls
    /// this alongside the stats reset; the newly selected log is then replayed in
    /// full, which re-derives everything that belongs to the new character. Learned
    /// durations stay — their store is install-wide, not session evidence.</summary>
    public void ResetSession()
    {
        lock (_lock)
        {
            _active.Clear();
            _recentCasts.Clear();
            _lastCastOf.Clear();
            _ownRankOf.Clear();
            _quickBuffAt = null;
            _seenLandings.Clear();
            _seenFades.Clear();
            _seenOwnCasts.Clear();
        }
        Changed?.Invoke();
    }

    private int _savePending;

    /// <summary>Debounced like StackingLedgerStore.Save (perf audit #13, the #3
    /// idiom): SaveStore is called under this tracker's lock on the ingest path —
    /// the synchronous write stalled tailing whenever a fade taught a duration.
    /// Flag now, one write ~2 s later; hosts call <see cref="Flush"/> at exit.
    /// Callers hold _lock.</summary>
    private void SaveStore()
    {
        if (_storePath is null) return;
        if (Interlocked.Exchange(ref _savePending, 1) == 1) return;
        Task.Run(async () =>
        {
            await Task.Delay(TimeSpan.FromSeconds(2)).ConfigureAwait(false);
            Interlocked.Exchange(ref _savePending, 0);
            Flush();
        });
    }

    /// <summary>Write now — hosts call this at exit. Serializes under the lock,
    /// writes outside it.</summary>
    public void Flush()
    {
        if (_storePath is not { } path) return;
        try
        {
            string json;
            lock (_lock) json = JsonSerializer.Serialize(_learned);
            ProfileJson.Write(path, json);
        }
        catch { /* best-effort */ }
    }
}
